mysite/main/urls.py
from main.views.Products.views import *
from main.views.Providers.views import *
from main.views.Sales.views import *
from main.views.Expenses.views import *
from main.views.Store.views import *
from main.views.Dashboard.views import *
from main.views.Vistas.views import *
from django.urls import path

app_name = 'main'

urlpatterns = [
    # productos
    path("products/list/", ProductsListView.as_view(), name="products_list"),
    path("products/add/", ProductsCreateView.as_view(), name="products_create"),
    path("products/update/<int:pk>/", ProductsUpdateView.as_view(), name="products_update"),
    path("products/delete/<int:pk>/", ProductsDeleteView.as_view(), name="products_delete"),
    path("products/form/", ProductsFormView.as_view(), name="products_form"),
    # proveedores
    path("providers/list/", ProvidersListView.as_view(), name="providers_list"),
    path("providers/add/", ProvidersCreateView.as_view(), name="providers_create"),
    path("providers/update/<int:pk>/", ProvidersUpdateView.as_view(), name="providers_update"),
    path("providers/delete/<int:pk>/", ProvidersDeleteView.as_view(), name="providers_delete"),
    # ventas
    path("sales/list/", SalesListView.as_view(), name="sales_list"),
    path("sales/add/", SalesCreateView.as_view(), name="sales_create"),
    path("sales/update/<int:pk>/", SalesUpdateView.as_view(), name="sales_update"),
    path("sales/delete/<int:pk>/", SalesDeleteView.as_view(), name="sales_delete"),
    # gastos
    path("expenses/list/", ExpensesListView.as_view(), name="expenses_list"),
    path("expenses/add/", ExpensesCreateView.as_view(), name="expenses_create"),
    path("expenses/update/<int:pk>/", ExpensesUpdateView.as_view(), name="sexpenses_update"),
    path("expenses/delete/<int:pk>/", ExpensesDeleteView.as_view(), name="expenses_delete"),
    # almacenes
    path("store/list/", StoreListView.as_view(), name="store_list"),
    path("store/add/", StoreCreateView.as_view(), name="store_create"),
    path("store/update/<int:pk>/", StoreUpdateView.as_view(), name="store_update"),
    path("store/delete/<int:pk>/", StoreDeleteView.as_view(), name="store_delete"),
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # vistas
    path('prod_prov/', Prod_ProvView, name='prod_prov'),
    path('prod_sales/', Prod_SalesView, name='prod_sales'),
    path('prod_store/', Prod_StoreView, name='prod_store'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import IndexView


urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('login/', include("login.urls")),
    path('main/', include("main.urls")),    
]

mysite/main/views/Dashboard/views.py
from django.db.models.aggregates import Sum
from django.db.models import Sum
from django.db.models.fields import DecimalField, FloatField
from main.models import Ventas
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Coalesce
from datetime import datetime


class DashboardView(TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_graph_sales_months(self):
        data = []
        try:
            year = datetime.now().year
            for m in range(1, 13):        
                total = Ventas.objects.filter(fecha_de_venta__year=year, fecha_de_venta__month=m).aggregate(r=Coalesce(Sum('monto_total', output_field=FloatField()), 0.00)).get('r')
                data.append(total)
        except Exception as e:            
            print(e)        
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Panel de administrador'
        context['graph_sales_months'] = self.get_graph_sales_months()
        return context

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} {{title}} {% endblock %}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"/>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/plugins/fontawesome-free/css/all.min.css' %}"/>
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/css/adminlte.min.css' %}"/>
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.1.0/js/adminlte.min.js' %}"></script>
    <!-- SweetAlert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Mis Funciones -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Mis Styles -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

    <!-- Block Head -->
    {% block head %}

    {% endblock %}
  </head>

  {% block body %}

  {% endblock %}
</html>

mysite/templates/body.html
{% extends "base.html" %}

{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">Bienvenido <small>EQUIPO 4</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'main:dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}
                
                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    </body>
{% endblock %}

mysite/templates/dashboard.html
{% extends "body.html" %} {% load static %} 


{% block head %}
<script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock %} 

{% block content %}

<div class="row">
  <div class="col-md-4">
    <a href="{% url 'main:prod_store' %}" class="navbar-brand">
      <img
        src="{% static 'img/HP1.png' %}"
        alt="AdminLTE Logo"
        class="image-logo"
        style="opacity: 0.8"
        width="350px"
      />
    </a>
  </div>
  <!-- /.col -->
  <div class="col-md-4">
    <a href="{% url 'main:prod_prov' %}" class="navbar-brand">
      <img
        src="{% static 'img/HP2.png' %}"
        alt="AdminLTE Logo"
        class="image-logo"
        style="opacity: 0.8"
        width="350px"
      />
    </a>
  </div>
  <!-- /.col -->
  <div class="col-md-4">
    <a href="{% url 'main:prod_sales' %}" class="navbar-brand">
      <img
        src="{% static 'img/HP3.png' %}"
        alt="AdminLTE Logo"
        class="image-logo"
        style="opacity: 0.8"
        width="350px"
      />
    </a>
  </div>
</div> 

<hr>
<hr>

  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div id="container"></div>
        <hr>
      </div>
    </div>    
  </div>

  <script type="application/javascript">
    Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Reporte de ventas'
    },
    subtitle: {
        text: 'Reporte de columnas'
    },
    xAxis: {
        categories: [
            'Enero',
            'Febrero',
            'Marzo',
            'Abril',
            'Mayo',
            'Junio',
            'Julio',
            'Agosto',
            'Septiembre',
            'Octubre',
            'Noviembre',
            'Diciembre'
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Valores $'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f} $</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [{         
        name: 'Porcentajes de venta',
        showInLegend: false,
        colorByPoint: true,
        data: {{ graph_sales_months|safe }} 
    }]
});
  
  </script>
{% endblock content %}

mysite/templates/delete.html
{% extends "body.html" %}
{% load widget_tweaks %} {% comment %} personalizar form {% endcomment %}
{% load static %}

{% block content %}
    <form method="post" action=".">
        <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-trash"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            <div class="alert alert-danger alert-dismissible">
                <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                ¿Estas seguro de eliminar el registro con ID {{ object.id }}?
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-save"></i> Si, aceptar
            </button>
            <a href="{{ list_url }}" class="btn btn-info">
                <i class="fas fa-times"></i> Cancelar
            </a>
        </div>
    </div>
    </form>

    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            //var parameters = $(this).serializeArray();
            //console.log(parameters);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: {},
                DataType: 'json'
            }).done(function(data) {
                if(!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function(jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function(data) {

            });
        });
    </script>
{% endblock %}

mysite/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">.</div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2021 <a href="https://adminlte.io">Equipos de Seguridad Industrial</a>.</strong> Todos los Derechos Reservados.

</footer>

mysite/templates/form.html
{% extends "body.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
    <form method="post" action=".">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">

                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro.</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="name">{{ field.label }}</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                     </div>
                {% endfor %}

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = $(this).serializeArray();
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                DataType: 'json'
            }).done(function(data) {
                if(!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}'; // retornamos a la url de la lista
                    return false;
                }
                message_error(data.error); // mi funcion js
                
            }).fail(function(jqXHR, textStatus, errorThrown) {

            }).always(function(data) {

            });
        });
    </script>
{% endblock %}

mysite/templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark-gray">
    <div class="container">
        <a href="{% url 'main:dashboard' %}" class="navbar-brand">
            <img src="{% static 'img/logo-mit.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light"></span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'main:dashboard' %}" class="nav-link"><i class="fas fa-home"></i>Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i>Mantenimientos</a>                       
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'main:products_list' %}" class="dropdown-item"><i class="fas fa-truck-loading"></i> Productos</a></li>
                        <li><a href="{% url 'main:providers_list' %}" class="dropdown-item"><i class="fas fa-boxes"></i> Proveedores</a></li>              
                        <li><a href="{% url 'main:sales_list' %}" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                        <li><a href="{% url 'main:expenses_list' %}" class="dropdown-item"><i class="fas fa-money-bill-wave"></i> Gastos</a></li>
                        <li><a href="{% url 'main:store_list' %}" class="dropdown-item"><i class="fas fa-store-alt"></i> Almacenes</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-file"></i>Informes</a>                       
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'main:prod_store' %}" class="dropdown-item"><i class="fas fa-cubes"></i> Consulta Stock</a></li>
                        <li><a href="{% url 'main:prod_prov' %}" class="dropdown-item"><i class="fas fa-handshake"></i> Consulta Proveedores</a></li>              
                        <li><a href="{% url 'main:prod_sales' %}" class="dropdown-item"><i class="fas fa-chart-bar"></i> Informe Ventas</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="fas fa-users-cog"></i> {{ request.user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">
                        Último Acceso: 12 de Abril de 2021
                    </span>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-edit mr-2"></i> Editar perfil
                        <span class="float-right text-muted text-sm">3 mins</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <i class="fas fa-lock mr-2"></i> Editar password
                        <span class="float-right text-muted text-sm">12 hours</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">
                        <p>Este sistema te permitira realizar diferentes actividades</p>
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="fas fa-power-off" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

mysite/templates/home.html
{% extends "body.html" %}

{% block body %}
<h1>Home Page</h1>
{% endblock %}

mysite/templates/list.html
{% extends "body.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    {% block head_list %}

    {% endblock %}

{% endblock %}

{% block content %}
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table" id="data">
                <thead>
                {% block columns %}

                {% endblock %}
                </thead>
                <tbody>
                {% block rows %}

                {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            <a href="{{ create_url }}" class="btn btn-primary btnTest">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
            {% comment %} <a href="{{ list_url }}" class="btn btn-success btnTest">
                <i class="fas fa-sync"></i> Actualizar
            </a> {% endcomment %}
        </div>
    </div>
{% endblock %}

<!--Cuando se cargue la pagina que autamaticamente active la configuracion de data table-->
{% block javascript %}
    <script type="application/javascript">
        $(function() {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });

            $('.btnTest').on('click', function() {
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {id:789452},
                    DataType: 'json'
                }).done(function(data) {

                }).fail(function(jqXHR, textStatus, errorThrown) {

                }).always(function(data) {

                });
            });
        });
    </script> 
{% endblock %}